backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'post'
    label: 'Blog'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "MM-DD-YYYY", time_format: "" }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean', required: false }
      - { label: 'Featured Image', name: 'featuredimage', widget: image, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Published', name: 'published', widget: 'hidden', default: true }
